### ISSUE TITLE
golang: Cannot insert double quote in `raw_string_literal`

### ISSUE THREAD

**Issue by nykma** [manateelazycat/grammatical-edit#11]
## Code

> `|` means point.

```go
type Test struct {
  Aaa string `json:|`
}
```

Then press `"` ( `(grammatical-edit-double-quote)` )

## Expect
```go
type Test struct {
  Aaa string `json:"|`
}
```
## Actual

An error will occur in minibuffer: `End position is smaller than start position` .

##  Misc

`tree-sitter-debug-mode` : 

```
source_file:
  type_declaration:
    type_spec:
      type_identifier:
      struct_type:
        field_declaration_list:
          field_declaration:
            field_identifier:
            type_identifier:
            raw_string_literal:
```

Inserting double quote in string literal should not change the whole tree, so I guess there's no need to do a grammatical edit here?
