### ISSUE TITLE
Unexpected behaviour in golang when performing `grammatical-edit-kill`

### ISSUE THREAD

**Issue by nykma** [manateelazycat/grammatical-edit#3]
## Code

>  `|` indicates point

```go
package main

var (
	Foo = "1234|567"
	Bar = "abcdefg"
)
```
Then execute `grammatical-edit-kill` command.

## Expected 

```go
package main

var (
	Foo = "1234|"
	Bar = "abcdefg"
)
```

## Actual

```go
package main

var (
	Foo = "1234|abcdefg"
)
```

## Misc
- `tree-sitter-mode` and `grammatical-edit-mode` both enabled.

- `tree-sitter-debug-mode` of original buffer:

```
source_file:
  package_clause:
    package_identifier:
  var_declaration:
    var_spec:
      identifier:
      expression_list:
        interpreted_string_literal:
    var_spec:
      identifier:
      expression_list:
        interpreted_string_literal:
```
