### ISSUE TITLE
support c++ string_literal and raw_string_literal

### ISSUE THREAD

**Issue by xhcoding** [manateelazycat/grammatical-edit#4]
```
int main(int argc, char* argv[]) {
    std::string tmp = "abc12345";
    std::string r_tmp = R"(abc12345)";
    return 0;
}

```
tree-sitter-debug-mode

```
translation_unit:
  function_definition:
    primitive_type:
    function_declarator:
      identifier:
      parameter_list:
        parameter_declaration:
          primitive_type:
          identifier:
        parameter_declaration:
          primitive_type:
          pointer_declarator:
            array_declarator:
              identifier:
    compound_statement:
      declaration:
        scoped_type_identifier:
          namespace_identifier:
          type_identifier:
        init_declarator:
          identifier:
          string_literal:
      declaration:
        scoped_type_identifier:
          namespace_identifier:
          type_identifier:
        init_declarator:
          identifier:
          raw_string_literal:
      return_statement:
        number_literal:

```
